// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Revised_MakeTable
arma::mat Revised_MakeTable(unsigned int n, arma::uvec vec_Index_lk, arma::uvec vec_Index_qk);
RcppExport SEXP _NeQTL_Revised_MakeTable(SEXP nSEXP, SEXP vec_Index_lkSEXP, SEXP vec_Index_qkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type vec_Index_lk(vec_Index_lkSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type vec_Index_qk(vec_Index_qkSEXP);
    rcpp_result_gen = Rcpp::wrap(Revised_MakeTable(n, vec_Index_lk, vec_Index_qk));
    return rcpp_result_gen;
END_RCPP
}
// Revised_Get_skql
List Revised_Get_skql(arma::vec vec_skl, arma::vec vec_skq, arma::vec vec_Index_lk, arma::vec vec_Index_qk);
RcppExport SEXP _NeQTL_Revised_Get_skql(SEXP vec_sklSEXP, SEXP vec_skqSEXP, SEXP vec_Index_lkSEXP, SEXP vec_Index_qkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vec_skl(vec_sklSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vec_skq(vec_skqSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vec_Index_lk(vec_Index_lkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vec_Index_qk(vec_Index_qkSEXP);
    rcpp_result_gen = Rcpp::wrap(Revised_Get_skql(vec_skl, vec_skq, vec_Index_lk, vec_Index_qk));
    return rcpp_result_gen;
END_RCPP
}
// Revised_Get_Cond_Prob
List Revised_Get_Cond_Prob(const Rcpp::DataFrame DM, bool b_qk, bool bDisplay, int n_Elems);
RcppExport SEXP _NeQTL_Revised_Get_Cond_Prob(SEXP DMSEXP, SEXP b_qkSEXP, SEXP bDisplaySEXP, SEXP n_ElemsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type DM(DMSEXP);
    Rcpp::traits::input_parameter< bool >::type b_qk(b_qkSEXP);
    Rcpp::traits::input_parameter< bool >::type bDisplay(bDisplaySEXP);
    Rcpp::traits::input_parameter< int >::type n_Elems(n_ElemsSEXP);
    rcpp_result_gen = Rcpp::wrap(Revised_Get_Cond_Prob(DM, b_qk, bDisplay, n_Elems));
    return rcpp_result_gen;
END_RCPP
}
// Get_Final_Result_Neighbor
List Get_Final_Result_Neighbor(arma::vec lk_index, arma::vec qk_index, arma::vec qNk_index, arma::vec prob_skq_qk1lk0, arma::vec prob_skq_qk1lk1, arma::vec prob_skq_qk0lk0, arma::vec prob_skq_qk0lk1, arma::vec prob_skl_qk1lk0, arma::vec prob_skl_qk1lk1, arma::vec prob_skl_qk0lk0, arma::vec prob_skl_qk0lk1, arma::vec prob_qNk_qk_0, arma::vec prob_qNk_qk_1, double prob_lk0_qk0, double prob_lk0_qk1, double prob_lk1_qk0, double prob_lk1_qk1, double prob_qk0_lk0, double prob_qk0_lk1, double prob_qk1_lk0, double prob_qk1_lk1, double prob_qk0, double prob_qk1, double prob_lk0, double prob_lk1, int K);
RcppExport SEXP _NeQTL_Get_Final_Result_Neighbor(SEXP lk_indexSEXP, SEXP qk_indexSEXP, SEXP qNk_indexSEXP, SEXP prob_skq_qk1lk0SEXP, SEXP prob_skq_qk1lk1SEXP, SEXP prob_skq_qk0lk0SEXP, SEXP prob_skq_qk0lk1SEXP, SEXP prob_skl_qk1lk0SEXP, SEXP prob_skl_qk1lk1SEXP, SEXP prob_skl_qk0lk0SEXP, SEXP prob_skl_qk0lk1SEXP, SEXP prob_qNk_qk_0SEXP, SEXP prob_qNk_qk_1SEXP, SEXP prob_lk0_qk0SEXP, SEXP prob_lk0_qk1SEXP, SEXP prob_lk1_qk0SEXP, SEXP prob_lk1_qk1SEXP, SEXP prob_qk0_lk0SEXP, SEXP prob_qk0_lk1SEXP, SEXP prob_qk1_lk0SEXP, SEXP prob_qk1_lk1SEXP, SEXP prob_qk0SEXP, SEXP prob_qk1SEXP, SEXP prob_lk0SEXP, SEXP prob_lk1SEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lk_index(lk_indexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type qk_index(qk_indexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type qNk_index(qNk_indexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk1lk0(prob_skq_qk1lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk1lk1(prob_skq_qk1lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk0lk0(prob_skq_qk0lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk0lk1(prob_skq_qk0lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk1lk0(prob_skl_qk1lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk1lk1(prob_skl_qk1lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk0lk0(prob_skl_qk0lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk0lk1(prob_skl_qk0lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_qNk_qk_0(prob_qNk_qk_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_qNk_qk_1(prob_qNk_qk_1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0_qk0(prob_lk0_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0_qk1(prob_lk0_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1_qk0(prob_lk1_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1_qk1(prob_lk1_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0_lk0(prob_qk0_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0_lk1(prob_qk0_lk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1_lk0(prob_qk1_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1_lk1(prob_qk1_lk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0(prob_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1(prob_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0(prob_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1(prob_lk1SEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(Get_Final_Result_Neighbor(lk_index, qk_index, qNk_index, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K));
    return rcpp_result_gen;
END_RCPP
}
// Gibbs_Sampler
List Gibbs_Sampler(arma::vec lk_index, arma::vec qk_index, arma::vec prob_skq_qk1lk0, arma::vec prob_skq_qk1lk1, arma::vec prob_skq_qk0lk0, arma::vec prob_skq_qk0lk1, arma::vec prob_skl_qk1lk0, arma::vec prob_skl_qk1lk1, arma::vec prob_skl_qk0lk0, arma::vec prob_skl_qk0lk1, arma::vec prob_qNk_qk_0, arma::vec prob_qNk_qk_1, arma::vec prob_lNk_lk_0, arma::vec prob_lNk_lk_1, double prob_lk0_qk0, double prob_lk0_qk1, double prob_lk1_qk0, double prob_lk1_qk1, double prob_qk0_lk0, double prob_qk0_lk1, double prob_qk1_lk0, double prob_qk1_lk1, double prob_qk0, double prob_qk1, double prob_lk0, double prob_lk1, int K);
RcppExport SEXP _NeQTL_Gibbs_Sampler(SEXP lk_indexSEXP, SEXP qk_indexSEXP, SEXP prob_skq_qk1lk0SEXP, SEXP prob_skq_qk1lk1SEXP, SEXP prob_skq_qk0lk0SEXP, SEXP prob_skq_qk0lk1SEXP, SEXP prob_skl_qk1lk0SEXP, SEXP prob_skl_qk1lk1SEXP, SEXP prob_skl_qk0lk0SEXP, SEXP prob_skl_qk0lk1SEXP, SEXP prob_qNk_qk_0SEXP, SEXP prob_qNk_qk_1SEXP, SEXP prob_lNk_lk_0SEXP, SEXP prob_lNk_lk_1SEXP, SEXP prob_lk0_qk0SEXP, SEXP prob_lk0_qk1SEXP, SEXP prob_lk1_qk0SEXP, SEXP prob_lk1_qk1SEXP, SEXP prob_qk0_lk0SEXP, SEXP prob_qk0_lk1SEXP, SEXP prob_qk1_lk0SEXP, SEXP prob_qk1_lk1SEXP, SEXP prob_qk0SEXP, SEXP prob_qk1SEXP, SEXP prob_lk0SEXP, SEXP prob_lk1SEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lk_index(lk_indexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type qk_index(qk_indexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk1lk0(prob_skq_qk1lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk1lk1(prob_skq_qk1lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk0lk0(prob_skq_qk0lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk0lk1(prob_skq_qk0lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk1lk0(prob_skl_qk1lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk1lk1(prob_skl_qk1lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk0lk0(prob_skl_qk0lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk0lk1(prob_skl_qk0lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_qNk_qk_0(prob_qNk_qk_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_qNk_qk_1(prob_qNk_qk_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_lNk_lk_0(prob_lNk_lk_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_lNk_lk_1(prob_lNk_lk_1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0_qk0(prob_lk0_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0_qk1(prob_lk0_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1_qk0(prob_lk1_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1_qk1(prob_lk1_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0_lk0(prob_qk0_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0_lk1(prob_qk0_lk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1_lk0(prob_qk1_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1_lk1(prob_qk1_lk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0(prob_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1(prob_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0(prob_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1(prob_lk1SEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(Gibbs_Sampler(lk_index, qk_index, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lNk_lk_0, prob_lNk_lk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K));
    return rcpp_result_gen;
END_RCPP
}
// Gibbs_Sampler2
List Gibbs_Sampler2(arma::vec lk_index, arma::vec qk_index, bool b_use_lNk, arma::vec prob_skq_qk1lk0, arma::vec prob_skq_qk1lk1, arma::vec prob_skq_qk0lk0, arma::vec prob_skq_qk0lk1, arma::vec prob_skl_qk1lk0, arma::vec prob_skl_qk1lk1, arma::vec prob_skl_qk0lk0, arma::vec prob_skl_qk0lk1, arma::vec prob_qNk_qk_0, arma::vec prob_qNk_qk_1, arma::vec prob_lNk_lk_0, arma::vec prob_lNk_lk_1, double prob_lk0_qk0, double prob_lk0_qk1, double prob_lk1_qk0, double prob_lk1_qk1, double prob_qk0_lk0, double prob_qk0_lk1, double prob_qk1_lk0, double prob_qk1_lk1, double prob_qk0, double prob_qk1, double prob_lk0, double prob_lk1, int K);
RcppExport SEXP _NeQTL_Gibbs_Sampler2(SEXP lk_indexSEXP, SEXP qk_indexSEXP, SEXP b_use_lNkSEXP, SEXP prob_skq_qk1lk0SEXP, SEXP prob_skq_qk1lk1SEXP, SEXP prob_skq_qk0lk0SEXP, SEXP prob_skq_qk0lk1SEXP, SEXP prob_skl_qk1lk0SEXP, SEXP prob_skl_qk1lk1SEXP, SEXP prob_skl_qk0lk0SEXP, SEXP prob_skl_qk0lk1SEXP, SEXP prob_qNk_qk_0SEXP, SEXP prob_qNk_qk_1SEXP, SEXP prob_lNk_lk_0SEXP, SEXP prob_lNk_lk_1SEXP, SEXP prob_lk0_qk0SEXP, SEXP prob_lk0_qk1SEXP, SEXP prob_lk1_qk0SEXP, SEXP prob_lk1_qk1SEXP, SEXP prob_qk0_lk0SEXP, SEXP prob_qk0_lk1SEXP, SEXP prob_qk1_lk0SEXP, SEXP prob_qk1_lk1SEXP, SEXP prob_qk0SEXP, SEXP prob_qk1SEXP, SEXP prob_lk0SEXP, SEXP prob_lk1SEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lk_index(lk_indexSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type qk_index(qk_indexSEXP);
    Rcpp::traits::input_parameter< bool >::type b_use_lNk(b_use_lNkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk1lk0(prob_skq_qk1lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk1lk1(prob_skq_qk1lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk0lk0(prob_skq_qk0lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skq_qk0lk1(prob_skq_qk0lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk1lk0(prob_skl_qk1lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk1lk1(prob_skl_qk1lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk0lk0(prob_skl_qk0lk0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_skl_qk0lk1(prob_skl_qk0lk1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_qNk_qk_0(prob_qNk_qk_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_qNk_qk_1(prob_qNk_qk_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_lNk_lk_0(prob_lNk_lk_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prob_lNk_lk_1(prob_lNk_lk_1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0_qk0(prob_lk0_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0_qk1(prob_lk0_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1_qk0(prob_lk1_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1_qk1(prob_lk1_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0_lk0(prob_qk0_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0_lk1(prob_qk0_lk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1_lk0(prob_qk1_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1_lk1(prob_qk1_lk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk0(prob_qk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_qk1(prob_qk1SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk0(prob_lk0SEXP);
    Rcpp::traits::input_parameter< double >::type prob_lk1(prob_lk1SEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(Gibbs_Sampler2(lk_index, qk_index, b_use_lNk, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lNk_lk_0, prob_lNk_lk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NeQTL_Revised_MakeTable", (DL_FUNC) &_NeQTL_Revised_MakeTable, 3},
    {"_NeQTL_Revised_Get_skql", (DL_FUNC) &_NeQTL_Revised_Get_skql, 4},
    {"_NeQTL_Revised_Get_Cond_Prob", (DL_FUNC) &_NeQTL_Revised_Get_Cond_Prob, 4},
    {"_NeQTL_Get_Final_Result_Neighbor", (DL_FUNC) &_NeQTL_Get_Final_Result_Neighbor, 26},
    {"_NeQTL_Gibbs_Sampler", (DL_FUNC) &_NeQTL_Gibbs_Sampler, 27},
    {"_NeQTL_Gibbs_Sampler2", (DL_FUNC) &_NeQTL_Gibbs_Sampler2, 28},
    {NULL, NULL, 0}
};

RcppExport void R_init_NeQTL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
