# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Revised_MakeTable <- function(n, vec_Index_lk, vec_Index_qk) {
    .Call(`_NeQTL_Revised_MakeTable`, n, vec_Index_lk, vec_Index_qk)
}

Revised_Get_skql <- function(vec_skl, vec_skq, vec_Index_lk, vec_Index_qk) {
    .Call(`_NeQTL_Revised_Get_skql`, vec_skl, vec_skq, vec_Index_lk, vec_Index_qk)
}

Revised_Get_Cond_Prob <- function(DM, b_qk = TRUE, bDisplay = FALSE, n_Elems = 1e+5L) {
    .Call(`_NeQTL_Revised_Get_Cond_Prob`, DM, b_qk, bDisplay, n_Elems)
}

Get_Final_Result_Neighbor <- function(lk_index, qk_index, qNk_index, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K) {
    .Call(`_NeQTL_Get_Final_Result_Neighbor`, lk_index, qk_index, qNk_index, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K)
}

Gibbs_Sampler <- function(lk_index, qk_index, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lNk_lk_0, prob_lNk_lk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K) {
    .Call(`_NeQTL_Gibbs_Sampler`, lk_index, qk_index, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lNk_lk_0, prob_lNk_lk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K)
}

Gibbs_Sampler2 <- function(lk_index, qk_index, b_use_lNk, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lNk_lk_0, prob_lNk_lk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K) {
    .Call(`_NeQTL_Gibbs_Sampler2`, lk_index, qk_index, b_use_lNk, prob_skq_qk1lk0, prob_skq_qk1lk1, prob_skq_qk0lk0, prob_skq_qk0lk1, prob_skl_qk1lk0, prob_skl_qk1lk1, prob_skl_qk0lk0, prob_skl_qk0lk1, prob_qNk_qk_0, prob_qNk_qk_1, prob_lNk_lk_0, prob_lNk_lk_1, prob_lk0_qk0, prob_lk0_qk1, prob_lk1_qk0, prob_lk1_qk1, prob_qk0_lk0, prob_qk0_lk1, prob_qk1_lk0, prob_qk1_lk1, prob_qk0, prob_qk1, prob_lk0, prob_lk1, K)
}

